#!/usr/bin/with-contenv bash

# samples are removed on init by the nginx base

# copy new samples
if [[ -d /defaults/nginx/subdomain-confs/ ]]; then
    find /defaults/nginx/subdomain-confs/ \
        -maxdepth 1 \
        -name "*.conf.sample" \
        -type f \
        -exec cp "{}" /config/nginx/subdomain-confs/ +
fi

if [[ -d /defaults/nginx/subfolder-confs/ ]]; then
    find /defaults/nginx/subfolder-confs/ \
        -maxdepth 1 \
        -name "*.conf.sample" \
        -type f \
        -exec cp "{}" /config/nginx/subfolder-confs/ +
fi
